import { Router, type IRouter } from "express";
import { ProxmoxServer } from "../db";
import { CreateProxmoxServerBody, DeleteProxmoxServerParams, GetProxmoxHealthParams, ListProxmoxVmsParams, StartProxmoxVmParams, StopProxmoxVmParams, SnapshotProxmoxVmParams, SnapshotProxmoxVmBody, UpdateProxmoxVmConfigParams, UpdateProxmoxVmConfigBody } from "@workspace/api-zod";
import { getProxmoxTicket,getProxmoxNodeStatus,listProxmoxVms,startVm,stopVm,createSnapshot,updateVmConfig } from "../services/proxmox.service";
import { encryptSecret } from "../services/credentials.service";
const router: IRouter=Router();
const attrs=["id","name","ip","port","username","nodeName","lastSeenStatus","lastCheckedAt","createdAt"];
type ProxmoxTicket = NonNullable<Awaited<ReturnType<typeof getProxmoxTicket>>>;
async function server(id:number){return ProxmoxServer.findByPk(id);}
router.get("/proxmox",async(_req,res)=>res.json(await ProxmoxServer.findAll({attributes:attrs,order:[["name","ASC"]]})));
router.post("/proxmox",async(req,res)=>{const p=CreateProxmoxServerBody.safeParse(req.body);if(!p.success){res.status(400).json({error:p.error.message});return;}const d=p.data;const s=await ProxmoxServer.create({name:d.name,ip:d.ip,port:d.port??8006,username:d.username,password:encryptSecret(d.password),nodeName:d.nodeName??"pve"});res.status(201).json(await ProxmoxServer.findByPk(s.get("id"),{attributes:attrs}));});
router.delete("/proxmox/:id",async(req,res)=>{const p=DeleteProxmoxServerParams.safeParse(req.params);if(!p.success){res.status(400).json({error:p.error.message});return;}if(!await ProxmoxServer.destroy({where:{id:p.data.id}})){res.status(404).json({error:"Proxmox server not found"});return;}res.sendStatus(204);});
async function load(req:any,res:any){const id=Number(req.params.id);const s=await server(id);if(!s){res.status(404).json({error:"Proxmox server not found"});return null;}return s.get({plain:true}) as any;}
router.get("/proxmox/:id/health",async(req,res)=>{const p=GetProxmoxHealthParams.safeParse(req.params);if(!p.success){res.status(400).json({error:p.error.message});return;}const s=await load(req,res);if(!s)return;const ticket=await getProxmoxTicket(s.ip,s.port,s.username,s.password);if(!ticket){await ProxmoxServer.update({lastSeenStatus:"OFFLINE",lastCheckedAt:new Date()},{where:{id:s.id}});res.json({serverId:s.id,status:"OFFLINE"});return;}const health=await getProxmoxNodeStatus(s.ip,s.port,ticket,s.nodeName);await ProxmoxServer.update({lastSeenStatus:health?"ONLINE":"OFFLINE",lastCheckedAt:new Date()},{where:{id:s.id}});res.json({serverId:s.id,status:health?"ONLINE":"OFFLINE",...health});});
router.get("/proxmox/:id/vms",async(req,res)=>{const p=ListProxmoxVmsParams.safeParse(req.params);if(!p.success){res.status(400).json({error:p.error.message});return;}const s=await load(req,res);if(!s)return;const t=await getProxmoxTicket(s.ip,s.port,s.username,s.password);res.json(t?await listProxmoxVms(s.ip,s.port,t,s.nodeName):[]);});
async function vmAction(req:any,res:any,fn:(s:any,t:ProxmoxTicket,p:number)=>Promise<any>){const s=await load(req,res);if(!s)return;const t=await getProxmoxTicket(s.ip,s.port,s.username,s.password);if(!t){res.json({success:false,message:"No se pudo autenticar con Proxmox"});return;}res.json(await fn(s,t,Number(req.params.vmid)));}
router.post("/proxmox/:id/vms/:vmid/start",async(req,res)=>{const p=StartProxmoxVmParams.safeParse(req.params);if(!p.success){res.status(400).json({error:p.error.message});return;}void vmAction(req,res,(s,t,v)=>startVm(s.ip,s.port,t,s.nodeName,v));});
router.post("/proxmox/:id/vms/:vmid/stop",async(req,res)=>{const p=StopProxmoxVmParams.safeParse(req.params);if(!p.success){res.status(400).json({error:p.error.message});return;}void vmAction(req,res,(s,t,v)=>stopVm(s.ip,s.port,t,s.nodeName,v));});
router.post("/proxmox/:id/vms/:vmid/snapshot",async(req,res)=>{const p=SnapshotProxmoxVmParams.safeParse(req.params),b=SnapshotProxmoxVmBody.safeParse(req.body);if(!p.success){res.status(400).json({error:p.error.message});return;}if(!b.success){res.status(400).json({error:b.error.message});return;}void vmAction(req,res,(s,t,v)=>createSnapshot(s.ip,s.port,t,s.nodeName,v,b.data.snapname,b.data.description));});
router.patch("/proxmox/:id/vms/:vmid/config",async(req,res)=>{const p=UpdateProxmoxVmConfigParams.safeParse(req.params),b=UpdateProxmoxVmConfigBody.safeParse(req.body);if(!p.success){res.status(400).json({error:p.error.message});return;}if(!b.success){res.status(400).json({error:b.error.message});return;}void vmAction(req,res,(s,t,v)=>updateVmConfig(s.ip,s.port,t,s.nodeName,v,b.data));});
export default router;